### PR TITLE
[WIP] pythonconsole: Import plugin from Pluma

### PR DESCRIPTION
**Pull request by jefferyto**
Having the Python Console available makes experimenting and writing Python plugins much easier.

I have tested the plugin in Xed 3.6.6 (Linux Mint 22 MATE Edition) by manually installing the plugin, I have not done a full build/install test though.

### CODE REVIEW

**Comment by mtwebster** [comment]
Hi, this works ok, but it seems like we should import a few of the most useful modules by default (os, sys, etc...).

**Comment by jefferyto** [comment]
I'm not sure that would be a good idea in practice:

* The user/programmer is expected to explicitly import any necessary modules in every other Python context, including Python in command-line interactive mode
* Any definition of which modules are the most useful/used/etc. would be anecdotal/arbitrary

**Comment by clefebvre** [comment]
Don't modify po/ files in the PR. It would just get overwritten again on PO imports from Launchpad.

Can you explain the steps required for a user to execute code? This is not obvious at all in Pluma, despite the plugin being mentioned in the help contents.

**Comment by jefferyto** [comment]
> Don't modify po/ files in the PR. It would just get overwritten again on PO imports from Launchpad.

The changes have been removed.

> Can you explain the steps required for a user to execute code? This is not obvious at all in Pluma, despite the plugin being mentioned in the help contents.

1. Enable the plugin
2. Show the bottom panel
3. Select the Python Console tab
4. Enter code at the `>>>` prompt

**Comment by clefebvre** [comment]
Papercut bug: The very first time you enable the plugin and click the bottom bar toggle button, the bar doesn't expand properly.

OK, so.. as a user I see python console in the plugin list. Its description is clear enough, it gives me a console in the bottom bar. I click on the bottom bar and a python console appears (assuming we fix the issue above).

As a Python dev I recognize the fact that this is an interpreter session and my Xed window has already been instantiated for me and is available as `window`.

What do I do now? I'm not trying to be smart by asking this. It's not obvious to me why I would want to use a python console in Xed, even as a Python dev. If it's just to mess with Python I can do that in a terminal.. if it's to run what's in my document I'd rather right-click -> Run either on the whole document or on a text selection.. 

I'm also not sure Xed aims at being an IDE. It can highlight code but its main purpose is to just be a text editor.

**Comment by jefferyto** [comment]
> It's not obvious to me why I would want to use a python console in Xed

The purpose of the console is to make writing Python plugins for Xed easier. It is much easier and faster to explore APIs and try ideas out in the console rather than:

* Create a test plugin
* Restart Xed from a terminal
* Enable the plugin
* Check the terminal for error messages
* Repeat the process

Before I updated my [plugin](https://github.com/jefferyto/gedit-control-your-tabs) to support Xed I had to add the Python Console for myself to test things out inside Xed.

**Comment by jefferyto** [comment]
Is this blocked on the papercut issue or something else?

**Comment by jefferyto** [comment]
I have [forked](https://github.com/jefferyto/gedit-pythonconsole) the gedit plugin and will be maintaining that version going forward.

**Pull request closed without merging**
