### PR TITLE
Creation of plugin Word completion

### PR DESCRIPTION
**Pull request by mickaelalbertus**
I rewrite the gedit plugin for word completion in xed. Maybe I could add more options? Here a screenshot of the configuration dialog:

image

### CODE REVIEW

**Comment by clefebvre** [comment]
hi @mickaelalbertus,

Can we simplify this plugin a bit? We can enable/disable plugins already in the preferences... so this plugin can be installed without being enabled. With this in mind, why do we need a checkbox and a gsettings key for "Automatic completion"?

Other than that the wording of some of the sentences needs to be improved.

"Check if you want.. " -> this can be removed along with the checkbox.

"Minimal word for automatic completion" -> "Minimum word size for auto-completion".

The title of the dialog should be simplified also and only contain the name of the plugin, which itself should be simplified to "Auto-completion".

**Comment by mickaelalbertus** [comment]
Hi @clefebvre, I changed the sentences except "Check if you want.. " for now because I wanted to explain to users that they could use the plugin with the shortcut Ctrl+Space. It's for that reason that there is a checkbox: the plugin works even if it's not checked but the user have to type Ctrl+Space.
I think we can change the sentence but let the shortcut?

**Comment by clefebvre** [comment]
CI picked an error: configure.ac:220: error: required file 'plugins/wordcompletion/Makefile.in' not found

**Comment by JosephMcc** [comment]
I'd like to see the indentation in this cleaned up before it's merged. All code in xed should be 4 spaces. This isn't and the plugin.c file is all new code and has mixed indentation that needs to be cleaned up.

**Comment by mickaelalbertus** [comment]
I fix it. I made this plugin before installing the good software!

**Comment by clefebvre** [comment]
I'm not sure why it's working in CI :)

I get this locally in Mint 19: 

gcc: error: ENCHANT_CFLAGS@: Aucun fichier ou dossier de ce type
Makefile:551: recipe for target 'xed-wordcompletion-plugin.lo' failed
make[4]: *** [xed-wordcompletion-plugin.lo] Error 1

**Comment by clefebvre** [comment]
I get the feeling Makefile.in should be kept out (it's generated) and Makefile.am added instead.

**Comment by mickaelalbertus** [comment]
Let's try ^^

**Comment by JosephMcc** [comment]
Enchant is also going away. It's been causing multiple build issues for people lately with the way it's versioned and the removal of deprecated functionality breaking it. On my dev branch for 1.8, xed has been ported to gspell. The port also simplifies the spell plugin by a huge amount.

**Comment by clefebvre** [comment]
Ah, that makes sense... I couldn't understand why CI didn't spot the issue initially :)

**Pull request merged**
