### PR TITLE
Rework status selectors

### PR DESCRIPTION
**Pull request by TomaszGasior**
— Port Gedit's status bar menu button to Xed. Use it in the status bar.
— Port Gedit's highlight mode selector widget to Xed.
— Use popover with this widget instead looong unusable menu in the status bar.
— Use dialog with this widget instead submenus in View->Highlight mode.
— Remove some unneeded code (after these changes).

I am weak in C/GLib so probably this PR won't be merged because of code quality. But I hope someone better than me will use it as the base. Also, I know that popovers are not liked in desktops other than GNOME but in this concrete case, a popover is much more easy to use and convenient than looooong menu without the search feature. I prepared videos to show the difference. Please look at this.

Before: [before.mp4.zip](https://github.com/linuxmint/xed/files/2217362/before.mp4.zip)
After: [after.mp4.zip](https://github.com/linuxmint/xed/files/2217363/after.mp4.zip)

There are some issues which should be fixed. Unfortunately, I have no idea how to fix it.
— Sometimes xed produces this error: `(xed:23347): Gtk-CRITICAL **: 22:40:42.053: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed`
— Navigation inside highlight mode selection dialog is impossible without the mouse. This bug exists also in original Gedit and it's not fixed. See https://bugzilla.gnome.org/show_bug.cgi?id=795380
— Pressing enter inside popover does not close it. The same in Gedit: https://bugzilla.gnome.org/show_bug.cgi?id=771350

### CODE REVIEW

**Comment by TomaszGasior** [comment]
If popover is problematic we can try a different approach.
— You can keep highlight selector dialog introduced by my PR.
— You can give up the idea about popover.
— Instead, you can tweak status bar button menu this way: show only "Plain text", five last used syntaxes and "show more" menu items. "Show more" could open highlight selector dialog. 
— More; if someone will find time for it, it's possible to introduce favorite syntaxes. Only these could be shown in status bar popup menu.

Unfortunately, I am not able to implement these ideas in real life. ;(

**Comment by clefebvre** [comment]
Hi @TomaszGasior sorry for the delay.

Can you rebase this PR?

I'm not mad about the popover but from a usability point of view there's no arguing, this is a step forward. Overall I think this is a nice improvement for Xed and we should merge it.

Just a quick question about styling. Maybe @JosephMcc knows.. when you highlight the widgets for style/space-tabs in the status bar, they have contour/border in master, but not in this PR. Is that an issue with the PR or something we need to add in our themes?

**Comment by TomaszGasior** [comment]
I'm so sorry but currently, I am busy with other important things and I won't find time for this task. I hope someone better than me in C/GLib/GTK can fork my PR and make it better.

**Comment by TomaszGasior** [comment]
> Just a quick question about styling. Maybe @JosephMcc knows.. when you highlight the widgets for style/space-tabs in the status bar, they have contour/border in master, but not in this PR. Is that an issue with the PR or something we need to add in our themes?

This is related to changed made by me (exactly: changes which I ported from Gedit by copy&paste method).  Look at this file: https://github.com/TomaszGasior/xed/blob/highlight-selector/xed/xed-status-menu-button.c#L88

**Comment by JosephMcc** [comment]
@TomaszGasior If we want to use this, do you mind if I take your work and fix it up so it can be merged? If not, it can wait until you get to it ;)

**Pull request merged**
