### PR TITLE
xed-close-confirmation-dialog: fix scrolledwindow minimum height

### PR DESCRIPTION
**Pull request by itzexor**
Tested with gtk 3.18.
Before http://i.imgur.com/L2mIAnn.png
After http://i.imgur.com/hk6U6zV.png

### CODE REVIEW

**Comment by monsta** [comment]
Interesting, we don't see this issue in GTK+3 build Pluma (of which xed is a fork) with 3.18...

Maybe it's something with the theme you're using?

**Comment by itzexor** [comment]
It shows like the "before" picture with any of Adwaita, Mint-X, or High Contrast controls themes. Assuming "controls" is the type of theme that would affect that.

**Comment by itzexor** [comment]
Here is the PKGBUILD I'm using to build & package xed on arch, just in case it helps somehow:
https://gist.github.com/itzexor/8c4528a7dbfbdfcc57af

And this is the PKGBUILD for the repo version of pluma-gtk3 (which is the version i tested with):
https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pluma-gtk3&id=46456e4bd0dfc8860c43329f6e8d94ba88d78b13

**Comment by JosephMcc** [comment]
I've run into this before. I don't remember what gtk version I was running when it happened. It doesn't happen every time. In any case I don't see how this PR hurts anything.

**Pull request merged**
